friend/urls.py
from django.urls import path

from friend.views import (
    send_friend_request,
    friend_requests,
    accept_friend_request,
    decline_friend_request,
    remove_friend,
    cancel_friend_request,
    friend_list_view1,
)

app_name = "friend"

urlpatterns = [
    path('friend_request/', send_friend_request, name="friend-request"),
    path('friend_request/<user_id>/', friend_requests, name="friend-requests"),
    path('accept_friend_request/<friend_request_id>/', accept_friend_request, name="friend-request-accept"),
    path('friend_remove/', remove_friend, name="remove-friend"),
    path('decline_friend_request/<friend_request_id>', decline_friend_request, name="friend-request-decline"),
    path('friend_request_cancel/', cancel_friend_request, name="friend-request-cancel"),
    path('list', friend_list_view1, name="list"),


]

posts/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path("", views.index,name="index"),
    path("edit/<int:id>", views.edit,name="edit"),
    path("delete/<int:id>", views.delete,name="delete"),
    path("view/<int:id>", views.view,name="view"),
    path("view/<int:id>/comment",views.AddCommentView,name="add_comment"),
    path("comment/<int:id>",views.delComment,name="del_comment"),
    path("like/",views.like_post,name="like-post"),
    path('view/<int:id>/postlikes/', views.post_likes, name='post-likes'),
    
]

socialMedia/urls.py
from django.contrib import admin

from django.conf.urls.static import static
# from django.conf.urls import url
from django.conf import settings
from django.urls import path, include
from django.views.generic import TemplateView,RedirectView
from posts import views

urlpatterns = [
    path("", views.index,name='home'),
    path("", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('friend/',include("friend.urls")),

    path('posts/', include("posts.urls")),
    path('groups/', include("groups.urls")),
    path('messages/', include("msgnotifications.urls")), #route for messages and notifications

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path(r'',TemplateView.as_view(template_name='404.html')),
]

friend/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from msgnotifications.models import Notification
import datetime

class FriendList(models.Model):
    # one friend list to one user 
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="user" )
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='friendds' )

    def __str__(self):
        return self.user.username
    
    def add_friend(self, account):
        # Add a new friend

        if not account in self.friends.all():
            self.friends.add(account)
    
    def remove_friend(self, account):
        #Remove a friend 
         if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        #Initiate the action of unfriending someone.
        remover_friends_list = self #person terminating the friendship
        # Remove friend from remover friend list
        remover_friends_list.remove_friend(removee)

        # Remove friend from removee friend list
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        # is this a friend?
        if friend in self.friends.all():
            return True
        return False

class FriendRequest(models.Model):
    
    # A friend request consists of two main parts:
    #    1. SENDER:
    #        - Person sending/initiating the friend request 
    #    2. RECEIVER:
    #        - Person receiving the friend request

    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="receiver")
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp=datetime.datetime.now()

    def __str__(self):
        return self.sender.username

    def accept(self):
        # Accept a friend request
        # update both DENDER and RECEIVER friend lists
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender)
            sender_friend_list = FriendList.objects.get(user=self.sender)
            if sender_friend_list:
                sender_friend_list.add_friend(self.receiver)
                self.is_active = False
                self.save()
                text=str(self.receiver.username +" accepted your friend request")
                notify_instance = Notification.objects.create(sender=self.receiver, reciever=self.sender,text=text, notifyType="profileView",instance_id=self.receiver.id)
                notify_instance.save()
    
    def decline(self):
        # Decline a friend request
        #it is declined by setting the 'is_active' field to False
        self.is_active = False
        self.save()

    def cancel(self):
        #cancel a friend request
        # it is 'cancelled' by setting the 'is_active' field to False
        # this is only different with respect "declining" through the notification that 
        # is genertated
        self.is_active = False
        self.save()

friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import json
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from msgnotifications.models import Message,Notification

from accounts.models import UserProfile
from friend.models import FriendRequest, FriendList


def friend_requests(request, *args, **kwargs):
    context = {}
    user = request.user

    user_id = kwargs.get("user_id")
    account = User.objects.get(pk=user_id)
    if account == user:
        friend_requests = FriendRequest.objects.filter(
            receiver=account, is_active=True)
        context['friend_requests'] = friend_requests
    else:
        return HttpResponse("You can't view another users friend requests.")
    return render(request, "friend/friend_requests.html", context)


def send_friend_request(request, *args, **kwargs):

    user = request.user  # get authenticated user

    payload = {}
    if request.method == "POST":
        user_id = request.POST.get("receiver_user_id") #id of user who receive request
       
        receiver = User.objects.get(pk=user_id)
        friend_request = FriendRequest(sender=user, receiver= receiver)
        friend_request.save()
    else:
        return render(request,'unauthorized.html')
    return HttpResponse(json.dumps(payload), content_type="application/json")


def accept_friend_request(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "GET":
        friend_request_id = kwargs.get("friend_request_id")
        friend_request = FriendRequest.objects.get(pk= friend_request_id)
        friend_request.accept()
        payload['response'] = "Friend request accepted."
    else:
        return render(request,'unauthorized.html')
    return HttpResponse(json.dumps(payload), content_type="application/json")



def decline_friend_request(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "GET":
        friend_request_id = kwargs.get("friend_request_id")
        if friend_request_id:
            friend_request = FriendRequest.objects.get(pk=friend_request_id)
            if friend_request.receiver == user:  # checking that the request is mine to decline
                if friend_request:
                # found request then decline it
                    friend_request.decline()
                    payload['response'] = "Friend request declined."
                else:
                    payload['response'] = "Something went wrong."
            else:
                payload['response'] = "That is not your friend request to decline"
        else:
            payload['response'] = "Unable to decline that friend request."
    else:
        return render(request,'unauthorized.html')
    return HttpResponse(json.dumps(payload), content_type="application/json")


def remove_friend(request, *args, **kwargs):
    user = request.user
    payload = {}
    if request.method == "POST":
        user_id = request.POST.get("reciever_user_id")
        if user_id:
            try:
                removee = User.objects.get(pk=user_id)
                friend_list = FriendList.objects.get(user=user)
                friend_list.unfriend(removee)
                payload['response'] = "Friend Removed."
            except Exception as e:
                payload['response'] = f"something went wronghu: {str(e)}"
        else:
            payload['response'] = "Unable to remove that friend"
    else:
        return render(request,'unauthorized.html')
    return HttpResponse(json.dumps(payload), content_type="application/json")


def cancel_friend_request(request, *args, **kwargs):
    user = request.user
    payload= {}
    if request.method == "POST" :
        user_id = request.POST.get("receiver_user_id")
        if user_id:
            receiver = User.objects.get(pk=user_id)
            try:
                friend_requests = FriendRequest.objects.filter(sender=user, receiver= receiver, is_active=True)
            except Exception as e:
                payload['response'] = "Nothing to cancel. Friend request does not exist."

            # There should only ever be a single active friend request at any given time
            # Cancel them all just in case.
            if len(friend_requests) > 1:
                for request in friend_requests:
                    request.cancel()
                payload['response'] = "Friend request cancelled."
            else:
                # found the request. Now cancel it.
                friend_requests.first().cancel()
                payload['response'] = "Friend request cancelled."
        else:
            payload['response'] = "Unable to cancel that friend request."
    else:
        return render(request,'unauthorized.html')

    return HttpResponse(json.dumps(payload), content_type="application/json")

 
def friend_list_view1(request, *args, **kwargs):
    context = {}
    user = request.user
    try:
        friend_list = FriendList.objects.get(user=user)
    except FriendList.DoesNotExist:
        return render(request, "friend_list.html", context)
    friends = []  
    for friend in friend_list.friends.all():
        friends.append((friend))

    context['friends'] = friends
    notifyCounter=len(  Notification.objects.filter(reciever=request.user).filter(read=False) )
    context['notifyCounter']=notifyCounter
    friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
    context["checker"]={"friend_requests":friend_requests}
    return render(request, "friend_list.html", context)

friend/templates/friend/snippets/accept_friend_request.html
<script>
    function acceptFriendRequest(friend_request_id, uiUpdateFunction) {
       
		
        var url = "{% url 'friend:friend-request-accept' friend_request_id=453452554545456465454465 %}".replace("453452554545456465454465", friend_request_id)
        $.ajax({
            type: 'GET',
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function (data) {

                if (data['response'] == "Friend request accepted.") {
                    
                }
                else if (data['response'] != null) {
                }
            },
            error: function (data) {

            },
            complete: function (data) {
                    uiUpdateFunction()
                }
                
        });
    }
</script>

friend/templates/friend/snippets/cancel_friend_request.html
<script type="text/javascript">

    function cancelFriendRequest(id, uiUpdateFunction) {
        payload = {
            "csrfmiddlewaretoken": "{{ csrf_token }}",
            "receiver_user_id": id,
        }
        $.ajax({
            type: 'POST',
            dataType: "json",
            url: "{% url 'friend:friend-request-cancel' %}",
            data: payload,
            timeout: 5000,
            success: function (data) {
                console.log("SUCCESS", data)
                if (data['response'] == "Friend request cancelled.") {
                }
                else if (data['response'] != null) {
                    alert(data['response'])
                }
            },
            error: function (data) {
            },
            complete: function (data) {
                uiUpdateFunction()
            }

        });
    }
</script>

friend/templates/friend/snippets/decline_friend_request.html
<script type="text/javascript">
    function declineFriendRequest(friend_request_id, uiUpdateFunction) {
        var url = "{% url 'friend:friend-request-decline' friend_request_id=453452554545456465454465 %}".replace("453452554545456465454465", friend_request_id)

        $.ajax({
            type: "GET",
            dataType: "json",
            url: url,
            timeout: 5000,
            success: function (data) {
                if (data.response == "Friend request declined.") {

                }
                else if (data.response == null) {
                   
                }
            },
            error: function (data) {
                
            },
            complete: function (data) {
                uiUpdateFunction()
            },
        })
    }
</script>

friend/templates/friend/snippets/remove_friend.html
<script type="text/javascript">
    function removeFriend(id, uiUpadateFunction) {
        payload = {
            "csrfmiddlewaretoken": "{{csrf_token}}",
            "reciever_user_id": id,
        }
        $.ajax({
            type: "POST",
            dataType: "json",
            timeout: 5000,
            url: "{% url 'friend:remove-friend' %}",
            data: payload,
            success: function (data) {
                if (data.response == "Friend Removed.") {

                }
                else if (data.response != null) {
                    // alert(data.response)
                }
            },
            error: function (data) {
                alert("uh oh ")
            },
            complete: function (data) {
                uiUpadateFunction()
            },
        })
    }

</script>

friend/templates/friend/snippets/send_friend_request.html
<script type="text/javascript">

	function sendFriendRequest(id, uiUpdateFunction) {
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'friend:friend-request' %}",
			timeout: 5000,
			data: payload,
			success: function (data) {
				console.log("SUCCESS", data)
				if (data['response'] == "Friend request sent.") {
				}
				else if (data['response'] != null) {
					// alert(data['response'])
				}
			},
			error: function (data) {
			},
			complete: function (data) {
				uiUpdateFunction()
			}
		});
	}

</script>