accounts/urls.py
from django.contrib import admin
from django.urls import path ,include
from . import views

urlpatterns = [
    path("signup/", views.signup,name="signup"),
    path('logout_request/',views.logout_request,name='logout_request'),
    path("profile/<int:id>", views.profile,name="profile"),
    path("profile/<int:id>/about", views.about,name="about"),
    path("profile/<int:id>/edit",views.edit,name="editProfile"),

]

friend/urls.py
from django.urls import path

from friend.views import (
    send_friend_request,
    friend_requests,
    accept_friend_request,
    decline_friend_request,
    remove_friend,
    cancel_friend_request,
    friend_list_view1,
)

app_name = "friend"

urlpatterns = [
    path('friend_request/', send_friend_request, name="friend-request"),
    path('friend_request/<user_id>/', friend_requests, name="friend-requests"),
    path('accept_friend_request/<friend_request_id>/', accept_friend_request, name="friend-request-accept"),
    path('friend_remove/', remove_friend, name="remove-friend"),
    path('decline_friend_request/<friend_request_id>', decline_friend_request, name="friend-request-decline"),
    path('friend_request_cancel/', cancel_friend_request, name="friend-request-cancel"),
    path('list', friend_list_view1, name="list"),


]

posts/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path("", views.index,name="index"),
    path("edit/<int:id>", views.edit,name="edit"),
    path("delete/<int:id>", views.delete,name="delete"),
    path("view/<int:id>", views.view,name="view"),
    path("view/<int:id>/comment",views.AddCommentView,name="add_comment"),
    path("comment/<int:id>",views.delComment,name="del_comment"),
    path("like/",views.like_post,name="like-post"),
    path('view/<int:id>/postlikes/', views.post_likes, name='post-likes'),
    
]

socialMedia/urls.py
from django.contrib import admin

from django.conf.urls.static import static
# from django.conf.urls import url
from django.conf import settings
from django.urls import path, include
from django.views.generic import TemplateView,RedirectView
from posts import views

urlpatterns = [
    path("", views.index,name='home'),
    path("", include("accounts.urls")),
    path("", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('friend/',include("friend.urls")),

    path('posts/', include("posts.urls")),
    path('groups/', include("groups.urls")),
    path('messages/', include("msgnotifications.urls")), #route for messages and notifications

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path(r'',TemplateView.as_view(template_name='404.html')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from groups.models import Group

# Create your models here.


class UserProfile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name=models.CharField(max_length=50,null=False,blank=False)
    last_name=models.CharField(max_length=50,null=False,blank=False)
    email = models.EmailField(max_length=255, default=None,unique=True)
    country = models.CharField(max_length=30, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    birthdate = models.DateField(
        auto_now=False, auto_now_add=False, null=False, blank=False)
    about = models.TextField(max_length=500, null=True, blank=True)
    groups = models.ManyToManyField(Group)

    

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = "__all__"
        exclude=('user','groups')

accounts/views.py
# Create your views here.
from django.shortcuts import render ,redirect
from django.contrib.auth import authenticate , login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from .forms import UserProfileForm
from django.contrib.auth.decorators import login_required,permission_required
from posts.models import Post
from .models import UserProfile
from posts.forms import PostForm
# Fatima 
from django.conf import settings
from friend.friend_request_status import FriendRequestStatus
from friend.models import FriendList, FriendRequest
from friend.utils import get_friend_request_or_false


def signup(request):
    form = UserCreationForm(request.POST or None) 
    profile_form = UserProfileForm(request.POST,request.FILES or None)

    if form.is_valid() and profile_form.is_valid():
            form.save()

            profile = profile_form.save(commit = False)
          
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(username=username , password=password)
            profile.user = user
            profile.save()
            if user:
                login(request , user)
                return redirect("/posts/")
            
    context = {'profile_form' : profile_form ,'form' : form }
    return render(request , "registration/signup.html", context)


def about(request,id):
    
    user = User.objects.get(pk=id)
    context={}
    if user==request.user:
        context["is_self"]=True
        choice="user"
        friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
        context["friend_requests"]=friend_requests
    else:
        context["is_self"]=False
        choice="account"
    return render(request,'about.html',{
            choice:user,
            "checker":context 
        })


def edit(request, id):
    user = User.objects.get(pk=id)
    if request.user.id != id:
        return render(request,'unauthorized.html')
    user_profile = UserProfile.objects.get(user=id)
    form = UserCreationForm(request.POST or None, instance=user)
    profile_form = UserProfileForm(request.POST or None,request.FILES or None, instance=user_profile)
    friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
    if form.is_valid() and profile_form.is_valid():
        form.save()
        profile = profile_form.save(commit = False)
        profile.user = user
        profile.save()
        return redirect('profile',id)
    return render(request, 'accounts/editProfile.html', {
        'form': form,
        'profile':profile_form,
        'user': user,
        'checker':{
            'friend_requests':friend_requests
        }

    })

def profile(request,id):
    
    context ={}
    posts={}
    form={}
    account= User.objects.get(id=id)
    if  account:
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.userprofile.email
        context['avatar'] = account.userprofile.avatar
    try:
            friend_list = FriendList.objects.get(user=account)
    except FriendList.DoesNotExist:
            friend_list = FriendList(user=account)
            friend_list.save()
    friends = friend_list.friends.all()
    context['friends'] = friends

    #define template variables
    is_self = True
    is_friend = False
    request_sent =  FriendRequestStatus.NO_REQUEST_SENT.value # range: ENUM -> friend/friend_request_status.FriendRequestStatus
    friend_requests = None
    user = request.user #authenticated user 
    if user.is_authenticated and user != account:
        is_self = False
        if friends.filter(pk=user.id):
            is_friend = True
            posts=Post.objects.filter(owner_id=account.id).order_by('-created_at')
        else:
            is_friend = False
            # CASE1: Request has been sent from THEM to YOU: FriendRequestStatus.THEM_SENT_TO_YOU
            if get_friend_request_or_false(sender=account, receiver=user) != False:
                request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
                context['pending_friend_request_id'] = get_friend_request_or_false(sender=account, receiver=user).id
            # CASE2: Request has been sent from YOU to THEM: FriendRequestStatus.YOU_SENT_TO_THEM
            elif get_friend_request_or_false(sender=user, receiver=account) != False:
                request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value
            # CASE3: No request sent from YOU or THEM: FriendRequestStatus.NO_REQUEST_SENT
            else:
                request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
                
    elif not user.is_authenticated:
            is_self = False
    else:
        try:
            is_self = True
            posts=Post.objects.filter(owner_id=user.id).order_by('-created_at')
            # You look at your own profile
            friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
        except:
            pass

    # Set the template variables to the values
    context['is_self'] = is_self
    context['is_friend'] = is_friend
    context['request_sent'] = request_sent
    context['friend_requests'] = friend_requests
    return render(request, "profile.html",{
       "user":user,
       "account":account,
       "checker":context,
       "posts":posts,
       
   })

def logout_request(request):
    logout(request)
    return redirect('index')

accounts/templates/about.html
{% extends "profileLayout.html" %}

{% block content %}
<div class="profile-content">
    {% if checker.is_self == False %}
    <h2>Information about {{account.userprofile.first_name}}:</h2>
    {% else %}
    <h2>Information about {{user.userprofile.first_name}}:</h2>
    {% endif %}
    <br>

    {% if checker.is_self == False %}
    <h4 class="profile-about">Country: </h4>
    {{account.userprofile.country}}
    {% else %}
    <h4 class="profile-about">Country: </h4>
    {{user.userprofile.country}}
    {% endif %}

    <br>
    <br>
    {% if checker.is_self == False %}
    <h4 class="profile-about">Birthdate: </h4>
    {{account.userprofile.birthdate}}
    {% else %}
    <h4 class="profile-about">Birthdate: </h4>
    {{user.userprofile.birthdate}}
    {% endif %}
    <br>

    <br>
    <br><br>
    <hr>
    <h4 class="profile-about">About: </h4>
    {{user.userprofile.about}}

</div>
{% endblock %}

accounts/templates/profile.html
{% extends "profileLayout.html" %}

{% block content %}
<div class="profile-content">

	<h5>Feed Posts</h5>
	{% if checker.is_self %}
	<div class="post-topbar">
		<form action='{% url "index" %}' method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="row">
				<div class="col-10">
					{{ form.as_p}}
					<input class="post_input " name="content" placeholder="  What's in your mind?" />
					<input class="mt-2 " type="file" name="image" />


				</div>
				<div class="col-2">
					<button class="post btn" type="submit">Post</button>
				</div>
			</div>
		</form>
	</div>
	{% endif %}

	{% if posts %}
	{% for post in posts %}
	<hr>
	<div class="card text-center">
		<div class="card-header">
			<div class="row" style="text-align:left;">
				<p class="col-7 tex-left "><span style="color:#e44d3a;">Posted by:</span> {{post.owner}}
					{% if post.group != null %}
					<span style="color:#e44d3a;"> >> from group:</span> {{post.group }}
					{% endif %}
				</p>

				<div class="col-5" style="text-align:right;">
					<a href="{% url 'view' post.id%}" style="color:grey;" class="mx-3"><i class="fa fa-eye"
							aria-hidden="true"></i></a>
					{% if post.owner == request.user %}
					<a href="{% url 'edit' post.id%}" style="color:grey;" class="mx-3"><i class="fa fa-pen"
							aria-hidden="true"></i></a>
					<a href="{% url 'delete' post.id%}" style="color:grey;" class="mx-3"><i class="fa fa-trash"
							aria-hidden="true"></i></a>
					{% endif %}
				</div>

			</div>
		</div>
		<div class="card-body">
			<h5 class="card-text">{{post.content}}</h5>
			{% if post.image != null and post.image != ""%}
			<img src="/images/{{post.image }}" width="400px" />
			{% endif %}

		</div>
		<div class="card-footer text-muted d-flex">
			<p style="text-align:left;color:gray;font-size:12px;margin:0px">{{post.created_at}}</p>
			<div style="text-align:right;width:80%">
				<a href="{% url 'view' post.id%}" style="color:#e44d3a;"><i class="fa fa-comment mx-4 fa-lg "
						aria-hidden="true"></i></a>
				<form action="{% url 'like-post' %}" method="POST" style="display: inline-block;">
					{% csrf_token %}
					<input type="hidden" name="post_id" value="{{post.id}}">

					{% if request.user not in post.liked.all %}
					<button type="submit"
						style="background-color:#e44d3a;color:whitesmoke;width: 58px;height: 30px;line-height: 10px;font-size: medium;border-radius: 30px;">Like
					</button>
					{% else %}
					<button type="submit"
						style="background-color:#e47668;color:whitesmoke;width: 70px;height: 30px;line-height: 10px;font-size: medium;border-radius: 30px;">Unlike
					</button>
					{% endif %}

				</form>
				<strong>{{ post.liked.all.count }} likes</strong>
			</div>
		</div>
	</div>

	<hr>

	{% endfor %}
	{% elif checker.is_self == True %}
	<h3>You have no posts.</h3>
	<h4>Add a post now.</h4>

	{% elif checker.is_friend == False %}
	<h3>You can't view this user's post.</h3>
	<h4>Add him as friend.</h4>
	{% else %}
	<h3>This user has not posted anything yet.</h3>
	{% endif %}
</div>
{% endblock %}

accounts/templates/profileLayout.html
{% extends "layout.html" %}

{% block body %}
{% load active_link_tags %}
<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="alert alert-success" id="accepted" style="display:none;"  role="alert">
                Request confirmed! Friend added.
              </div>
              <div class="alert alert-danger" style="display:none;" id="deleted" role="alert">
                Friend have been removed.
              </div>
              <div class="alert alert-danger" style="display:none;" id="decline" role="alert">
                You have declined the request.
              </div>
            <div class="profile-sidebar">
                <div class="profile-userpic" style="display: flex;justify-content: center;">
                    {% if checker.is_self == False %}
                    <img src="{% if account.userprofile.avatar %} {{account.userprofile.avatar.url}} {% else %} /images/avatars/profile.jpeg {% endif %}"
                        class="img-responsive" alt="">
                    {% else %}
                    <img src="{% if user.userprofile.avatar %} {{user.userprofile.avatar.url}} {% else %} /images/avatars/profile.jpeg {% endif %}"
                        class="img-responsive" alt="">
                    {% endif %}

                </div>
                <div class="profile-usertitle">
                    {% if checker.is_self == False %}
                    <div class="profile-usertitle-name">
                        {{account.userprofile.first_name}} {{account.userprofile.last_name}}

                    </div>
                    {% else %}
                    <div class="profile-usertitle-name">
                        {{user.userprofile.first_name}} {{user.userprofile.last_name}}

                    </div>
                    {% endif %}
                    <div class="profile-usertitle-job">
                    </div>
                </div>
                <!---------------------------------------------------------------------------------------------------------------------------->
                <div>
                    <!-- THEM to YOU -->
                    {% if checker.request_sent == 0 %}
                    <div class="card m-2 p-4">
                        <div class="">
                            <span id="id_confirm_{{account.id}}" class="confirm-friend-request px-1 m-auto btn post"
                                onclick='triggerAcceptFriendRequest("{{checker.pending_friend_request_id}}")'><i
                                    class="fas fa-check-circle "></i> Confirm Request</span>

                            <span id="id_cancel_{{id}}" class="decline-friend-request  my-1 btn post "
                                onclick='triggerDeclineFriendRequest("{{checker.pending_friend_request_id}}")'><i
                                    class="fas fa-times-circle "></i> Decline Request</span>


                        </div>
                    </div>
                    {% endif %}
                    <!------------------>
                    <!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
                    {% if checker.is_friend == False and checker.is_self == False %}
                    <!-- You sent them a request -->
                    {% if checker.request_sent == 1 %}
                    <div class="profile-userbuttons">
                        <button class="post btn btn-sm" id="id_cancel_friend_request_btn"><i
                                class="fas fa-user-plus"></i>
                            Cancel Friend Request
                        </button>
                    </div>
                    {% endif %}
                    <!-- No requests have been sent -->
                    {% if checker.request_sent == -1 %}
                    <div class="profile-userbuttons">
                        <button class="post btn btn-sm" id="id_send_friend_request_btn"><i class="fas fa-user-plus"></i>
                            Send Friend Request
                        </button>
                    </div>
                    {% endif %}
                    {% endif %}

                    {% if checker.is_friend %}
                    <div class="profile-userbuttons d-flex flex-row align-items-center m-auto px-2">
                        <button class="btn btn-secondary m-auto " id="id_unfriend_btn">Unfriend</button>
                    </div>
                    {% endif %}

                </div>
                {% if checker.friend_requests  %}

                <!-- Friend requests -->
                <div class="d-flex flex-row align-items-center m-2 px-4">
                    <a href="{% url 'friend:friend-requests' user_id=user.id %}">
                        <div class="d-flex flex-row align-items-center justify-content-center icon-container"><span
                                class="friend-text btn post"><i class="fas fa-user-plus"></i> Friend Requests
                                ({{checker.friend_requests|length}})</span>
                        </div>
                    </a>
                </div>



                {% endif %}
                <!------->

                {% if checker.is_friend %}
                <a href="/messages/?id={{account.id}}">

                    <div class="d-flex flex-row align-items-center justify-content-center icon-container m-auto px-2">
                        <span class="post btn friend-text "><i class="far fa-envelope"></i> Message</span>

                    </div>
                </a>

                {% endif %}
                <!----------------------------------------------------------------------------------------------------------------------------->
                <div class="profile-usermenu">
                    <ul style="list-style: none;">
                        {% if checker.is_self == False %}
                        <li class="{% active_link 'profile' 'active' strict=True %}">
                            <a href="/profile/{{account.id}}">
                                <i class="fas fa-home"></i>
                                Posts </a>
                        </li>
                        <li class="{% active_link 'about' 'active' strict=True %}">
                            <a href="/profile/{{account.id}}/about">
                                <i class="fas fa-user"></i>
                                About </a>
                        </li>


                        {% else %}

                        <li class="{% active_link 'profile' 'active' strict=True %}">
                            <a href="/profile/{{user.id}}">
                                <i class="fas fa-home"></i>
                                Posts </a>
                        </li>
                        <li class="{% active_link 'about' 'active' strict=True %}">
                            <a href="/profile/{{user.id}}/about">
                                <i class="fas fa-user"></i>
                                About </a>
                        </li>
                        <li class="{% active_link 'list' 'active' strict=True %}">
                            <a href="{% url 'friend:list' %}">
                                <i class="fa fa-user-friends" aria-hidden="true"></i>
                                Friends </a>
                        </li>
                        <li class="{% active_link 'about' 'active' strict=True %}">
                            <a href="/profile/{{user.id}}/edit">
                                <i class="fas fa-pen"></i>
                                Edit Profile </a>
                        </li>

                        {% endif %}

                    </ul>
                </div>
                <!------------------------------------------------------>

            </div>
        </div>
        <div class="col-md-9">


            {% block content %}{% endblock %}
        </div>
    </div>
</div>


<script type="text/javascript">

    function uiReload() {
        location.reload();
    }
    var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
    if (sendFriendRequestBtn != null) {
        sendFriendRequestBtn.addEventListener("click", function () {
            sendFriendRequest("{{account.id}}", uiReload)
        })
    }
    var removeFriendBtn = document.getElementById("id_unfriend_btn")
    if (removeFriendBtn != null) {
        removeFriendBtn.addEventListener("click", function () {
            removeFriend("{{account.id}}", function(){
                var deletedDiv=document.getElementById("deleted");
			    deletedDiv.style.display="block";
			    setInterval(() => {
				uiReload()
			}, 1000);
            })
        })
    }

    function triggerAcceptFriendRequest(friend_request_id) {
        acceptFriendRequest(friend_request_id,function(){
            var acceptedDiv=document.getElementById("accepted");
			acceptedDiv.style.display="block";
			setInterval(() => {
				uiReload()
			}, 1000);
        })
    }

    var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
    if (cancelFriendRequestBtn != null) {
        cancelFriendRequestBtn.addEventListener("click", function () {
            cancelFriendRequest("{{account.id}}", uiReload)
        })
    }



    function triggerDeclineFriendRequest(friend_request_id) {
    
        declineFriendRequest(friend_request_id,function(){
            var declinedDiv=document.getElementById("decline");
			declinedDiv.style.display="block";
			setInterval(() => {
				uiReload()
			}, 1000);
        })
    }


</script>

{% include 'friend/snippets/send_friend_request.html' %}
{% include 'friend/snippets/decline_friend_request.html' %}
{% include 'friend/snippets/accept_friend_request.html' %}
{% include 'friend/snippets/remove_friend.html' %}
{% include 'friend/snippets/cancel_friend_request.html' %}


{% endblock %}